name = "tapkey-relay"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[durable_objects.bindings]]
name = "RELAY_SESSION"
class_name = "RelaySession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelaySession"]
