name: Build & Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: cachix/install-nix-action@v31

      - name: Build, sign, notarize, and package
        id: package
        run: |
          nix develop --command make package
          SHA="${GITHUB_SHA::7}"
          echo "zip_name=tapkey-${SHA}-arm64.zip" >> "$GITHUB_OUTPUT"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"
        env:
          AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}

      - name: Attest
        if: ${{ !github.event.repository.private }}
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-path: ${{ steps.package.outputs.zip_name }}

      - name: Create release
        run: |
          gh release create "$SHA" "$ZIP_NAME" \
            --title "tapkey $SHA" \
            --target "$GITHUB_SHA" \
            --generate-notes \
            --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHA: ${{ steps.package.outputs.sha }}
          ZIP_NAME: ${{ steps.package.outputs.zip_name }}
